export const FETCH_BUSINESS_REQUEST = "FETCH_BUSINESS_REQUEST";
export const FETCH_BUSINESS_SUCCESS = "FETCH_BUSINESS_SUCCESS";
export const FETCH_BUSINESS_FAILURE = "FETCH_BUSINESS_FAILURE";

export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAILURE = "CREATE_BUSINESS_FAILURE";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAILURE = "DELETE_BUSINESS_FAILURE";

export const FETCH_CLIENT_BUSINESS_REQUEST = "FETCH_CLIENT_BUSINESS_REQUEST";
export const FETCH_CLIENT_BUSINESS_SUCCESS = "FETCH_CLIENT_BUSINESS_SUCCESS";