export const DOCUMENT_FETCH_BY_UID = 'DOCUMENT_FETCH_BY_UID';
export const DOCUMENT_FETCH_ERROR = 'DOCUMENT_FETCH_ERROR';
export const DOCUMENT_FETCH_BY_UID_SUSSESS = 'DOCUMENT_FETCH_BY_UID_SUSSESS';

